{% set name = "klongpy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/klongpy-{{ version }}.tar.gz
  sha256: 11733baf3aad02f14ac437b218869b507a15a01fc5a922dd561923aa401df5d3

build:
  skip: true  # [py<39 or py>311]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy ~=1.26.4

test:
  imports:
    - klongpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/briangu/klongpy
  summary: Python implementation of Klong language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
