{% set name = "klongpy" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/klongpy-{{ version }}.tar.gz
  sha256: 1c88bb92dee85a816c2e26aa2566345b0b2655bcbe30a49fcfebd8a2a0d90656

build:
  skip: true  # [py<39 or py>311]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy ~=1.26.4

test:
  imports:
    - klongpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/briangu/klongpy
  summary: Python implementation of Klong language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
