{% set name = "klongpy" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/klongpy-{{ version }}.tar.gz
  sha256: a38e377f80421a6d4bf85b828cf011674170b523e714c05e3ceb3afd3314a5f9

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy ~=1.24.0

test:
  imports:
    - klongpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/briangu/klongpy
  summary: Python implementation of Klong language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
