{% set name = "klongpy" %}
{% set version = "0.3.69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/klongpy-{{ version }}.tar.gz
  sha256: f6876b758e754a34bb57e279628c95f12a10ea6a8f54979a0d7e2af75836192a

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.23.0,<1.24.dev0

test:
  imports:
    - klongpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/briangu/klongpy
  summary: Python implementation of Klong language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
