{% set name = "klongpy" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/klongpy-{{ version }}.tar.gz
  sha256: 6c242da56ada1dc39acdce5d96b1d204eff52fd68db227ed1148b1f7f1fdbe69

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy ~=1.24.4

test:
  imports:
    - klongpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/briangu/klongpy
  summary: Python implementation of Klong language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
